name: app_e_commerce
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  icons_launcher: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.0.0
  http: ^1.3.0
  bloc: ^9.0.0
  dartz: ^0.10.1
  connectivity_plus: ^6.1.2
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_image_slideshow: ^0.1.6
  cached_network_image: ^3.4.1


## flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#004182"
  image: assets/images/splash.png
  color_dark: "#004182"
  image_dark: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    icon_background_color: "#004182"
    image_dark: assets/images/splash.png
    icon_background_color_dark: "#004182"

icons_launcher:
  image_path: "assets/images/logo_pic.jpg"
  adaptive_background_color: "#2096F3"
  platforms:
    android:
      enable: true
    ios:
      enable: true



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  injectable_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
